name: JScrewIt Node.js CI

on:
  push:
    branches: ['**']
    tags-ignore: ['**']
  pull_request:
    branches: ['**']

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-node@v7
      with:
        node-version: '24'
    - run: |
        npm install
        npm run --workspaces make
        gulp lint
        gulp bundle:lib
    - uses: actions/upload-artifact@v7
      with:
        name: lib
        path: lib

  test:

    name: test (Node.js ${{ matrix.node-version }})

    needs: build

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['20', '22', '24', latest]

    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-node@v7
      with:
        node-version: ${{ matrix.node-version }}
    - uses: actions/download-artifact@v8
      with:
        name: lib
        path: lib
    - run: |
        npm install -D @types/mocha ebdd expectations mocha@4 postrequire
        npm test
